const types = {
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
    GET_PRICE: 'GET_PRICE',
    SEARCH_CONTRACT_ADDRESS: 'SEARCH_CONTRACT_ADDRESS',
    GET_INSCRIPTIONS: 'GET_INSCRIPTIONS'
}

export default types;
